/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const EditingStyle = IDL.Variant({
  'SoftGlow' : IDL.Null,
  'Vintage' : IDL.Null,
  'WarmTone' : IDL.Null,
  'CoolTone' : IDL.Null,
  'Vivid' : IDL.Null,
  'BlackAndWhite' : IDL.Null,
});
export const FullPhoto = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'editingStyle' : EditingStyle,
  'description' : IDL.Text,
  'blobId' : IDL.Text,
  'isPublic' : IDL.Bool,
  'uploadedAt' : IDL.Int,
});
export const PublicPhoto = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'editingStyle' : EditingStyle,
  'description' : IDL.Text,
  'blobId' : IDL.Text,
  'isPublic' : IDL.Bool,
  'uploadedAt' : IDL.Int,
});
export const CreatePhoto = IDL.Record({
  'title' : IDL.Text,
  'editingStyle' : EditingStyle,
  'description' : IDL.Text,
  'blobId' : IDL.Text,
  'isPublic' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPhoto' : IDL.Func([IDL.Text], [FullPhoto], ['query']),
  'getPublicPhotos' : IDL.Func([], [IDL.Vec(PublicPhoto)], ['query']),
  'getUserPhotos' : IDL.Func([], [IDL.Vec(FullPhoto)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'togglePublic' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'uploadPhoto' : IDL.Func([CreatePhoto], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const EditingStyle = IDL.Variant({
    'SoftGlow' : IDL.Null,
    'Vintage' : IDL.Null,
    'WarmTone' : IDL.Null,
    'CoolTone' : IDL.Null,
    'Vivid' : IDL.Null,
    'BlackAndWhite' : IDL.Null,
  });
  const FullPhoto = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'editingStyle' : EditingStyle,
    'description' : IDL.Text,
    'blobId' : IDL.Text,
    'isPublic' : IDL.Bool,
    'uploadedAt' : IDL.Int,
  });
  const PublicPhoto = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'editingStyle' : EditingStyle,
    'description' : IDL.Text,
    'blobId' : IDL.Text,
    'isPublic' : IDL.Bool,
    'uploadedAt' : IDL.Int,
  });
  const CreatePhoto = IDL.Record({
    'title' : IDL.Text,
    'editingStyle' : EditingStyle,
    'description' : IDL.Text,
    'blobId' : IDL.Text,
    'isPublic' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPhoto' : IDL.Func([IDL.Text], [FullPhoto], ['query']),
    'getPublicPhotos' : IDL.Func([], [IDL.Vec(PublicPhoto)], ['query']),
    'getUserPhotos' : IDL.Func([], [IDL.Vec(FullPhoto)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'togglePublic' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'uploadPhoto' : IDL.Func([CreatePhoto], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };